// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: common/common.proto

/* eslint-disable */

export interface SetStatusRequest {
  /** 主键id */
  id: number;
  /** 状态 */
  status: number;
}

export interface TreeOptionResponse {
  list: TreeOptionResponse_Option[];
}

export interface TreeOptionResponse_Option {
  /** 选项名 */
  label: string;
  /** 选项值 */
  value: number;
  /** 是否禁用 */
  disabled: boolean;
  /** 子节点树 */
  children: TreeOptionResponse_Option[];
}

export interface SelectOptionResponse {
  list: SelectOptionResponse_Option[];
}

export interface SelectOptionResponse_Option {
  /** 选项名 */
  label: string;
  /** 选项值 */
  value: number;
  /** 是否禁用 */
  disabled: boolean;
}

export interface AppTreeOptionResponse {
  list: AppTreeOptionResponse_Option[];
}

export interface AppTreeOptionResponse_Option {
  /** 值。必填 */
  value: string;
  /** 显示文字。必填 */
  text: string;
  /** 是否默认选中。默认值false */
  selected: boolean;
  /** 是否禁用。默认值false */
  disable: boolean;
  /** 子节点树 */
  children: AppTreeOptionResponse_Option[];
}
