// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: common/enum.proto

/* eslint-disable */

/** 状态 */
export enum Status {
  UNKNOWN = 0,
  /** ENABLE - 启用 */
  ENABLE = 1,
  /** DISABLE - 禁用 */
  DISABLE = 2,
}

/** 系统配置位置 */
export enum BaseConfigSite {
  UNKNOWN_BCS = 0,
  /** SYSTEM - 系统内使用 */
  SYSTEM = 1,
  /** ADMIN - 管理端 */
  ADMIN = 2,
  /** APP - 移动端 */
  APP = 3,
}

/** 系统配置类型 */
export enum BaseConfigType {
  UNKNOWN_BCT = 0,
  /** TEXT - 文本 */
  TEXT = 1,
  /** IMAGE - 图片 */
  IMAGE = 2,
  /** RICH_TEXT - 富文本 */
  RICH_TEXT = 3,
}

/** 定时任务日志状态 */
export enum BaseJobLogStatus {
  UNKNOWN_BJLS = 0,
  /** SUCCESS - 成功 */
  SUCCESS = 1,
  /** FAIL - 失败 */
  FAIL = 2,
}

/** 菜单类型 */
export enum BaseMenuType {
  UNKNOWN_MT = 0,
  /** FOLDER - 目录 */
  FOLDER = 1,
  /** MENU - 菜单 */
  MENU = 2,
  /** BUTTON - 按钮 */
  BUTTON = 3,
  /** EXT_LINK - 外部链接 */
  EXT_LINK = 4,
}

/** 角色数据范围 */
export enum BaseRoleDataScope {
  UNKNOWN_RDS = 0,
  /** ALL - 全部数据 */
  ALL = 1,
  /** DEPT_AND_CHILDREN - 部门及子部门数据 */
  DEPT_AND_CHILDREN = 2,
  /** SELF_DEPT - 本部门数据 */
  SELF_DEPT = 3,
  /** SELF_USER - 本人数据 */
  SELF_USER = 4,
}

/** 用户性别 */
export enum BaseUserGender {
  UNKNOWN_BUG = 0,
  /** SECRET - 保密 */
  SECRET = 1,
  /** BOY - 男 */
  BOY = 2,
  /** GIRL - 禁用 */
  GIRL = 3,
}

/** 用户门店审核状态 */
export enum UserStoreStatus {
  UNKNOWN_USS = 0,
  /** PENDING_REVIEW - 待审核 */
  PENDING_REVIEW = 1,
  /** FAILED_REVIEW - 审核失败 */
  FAILED_REVIEW = 2,
  /** APPROVED - 审核通过 */
  APPROVED = 3,
}

/** 商品状态 */
export enum GoodsStatus {
  UNKNOWN_GS = 0,
  /** PUT_ON - 已上架 */
  PUT_ON = 1,
  /** PULL_OFF - 已下架 */
  PULL_OFF = 2,
}

/** 订单状态 */
export enum OrderStatus {
  UNKNOWN_OS = 0,
  /** CREATED - 待付款 */
  CREATED = 1,
  /** PAID - 待发货 */
  PAID = 2,
  /** SHIPPED - 待收货 */
  SHIPPED = 3,
  /** RECEIVED - 已完成 */
  RECEIVED = 4,
  /** REFUNDING - 已退款 */
  REFUNDING = 97,
  /** CANCELED - 已取消 */
  CANCELED = 98,
  /** DELETED - 已删除 */
  DELETED = 99,
}

/** 订单支付方式 */
export enum OrderPayType {
  UNKNOWN_OPT = 0,
  /** ONLINE_PAY - 在线支付 */
  ONLINE_PAY = 1,
  /** CASH_ON_DELIVERY - 货到付款 */
  CASH_ON_DELIVERY = 2,
}

/** 订单支付渠道 */
export enum OrderPayChannel {
  UNKNOWN_OPC = 0,
  /** WX_PAY - 微信支付 */
  WX_PAY = 1,
  /** UNION_PAY - 银联支付 */
  UNION_PAY = 2,
}

/** 订单配送时间 */
export enum OrderDeliveryTime {
  UNKNOWN_ODT = 0,
  /** ALL_TIME - 时间不限 (周一至周日) */
  ALL_TIME = 1,
  /** WEEKDAY - 工作日送 (周一至周五) */
  WEEKDAY = 2,
  /** WEEKEND - 周末配送 (周六至周日) */
  WEEKEND = 3,
}

/** 订单取消原因 */
export enum OrderCancelReason {
  UNKNOWN_OCR = 0,
  /** CANCEL_GOODS_NO_STOCK - 商品无货 */
  CANCEL_GOODS_NO_STOCK = 1,
  /** CANCEL_SELF - 不想要了 */
  CANCEL_SELF = 2,
  /** CANCEL_GOODS_ERROR - 商品信息填错了 */
  CANCEL_GOODS_ERROR = 3,
  /** CANCEL_ADDRESS_ERROR - 地址信息填写错误 */
  CANCEL_ADDRESS_ERROR = 4,
  /** CANCEL_GOODS_DISCOUNT - 商品降价 */
  CANCEL_GOODS_DISCOUNT = 5,
  /** CANCEL_OTHER - 其它 */
  CANCEL_OTHER = 6,
}

/** 订单对帐状态 */
export enum OrderBillStatus {
  UNKNOWN_OBS = 0,
  /** NO_CHECK - 未对账 */
  NO_CHECK = 1,
  /** CHECK_SUCCESS - 对账成功 */
  CHECK_SUCCESS = 2,
  /** CHECK_FAIL - 对账失败 */
  CHECK_FAIL = 3,
}

/** 订单退款原因 */
export enum OrderRefundReason {
  UNKNOWN_ORR = 0,
  /** REFUND_GOODS_NO_STOCK - 商品无货 */
  REFUND_GOODS_NO_STOCK = 1,
  /** REFUND_SELF - 不想要了 */
  REFUND_SELF = 2,
  /** REFUND_GOODS_ERROR - 商品信息填错了 */
  REFUND_GOODS_ERROR = 3,
  /** REFUND_ADDRESS_ERROR - 地址信息填写错误 */
  REFUND_ADDRESS_ERROR = 4,
  /** REFUND_GOODS_DISCOUNT - 商品降价 */
  REFUND_GOODS_DISCOUNT = 5,
  /** REFUND_OTHER - 其它 */
  REFUND_OTHER = 6,
}

/** 轮播图位置 */
export enum ShopBannerSite {
  UNKNOWN_SBS = 0,
  /** INDEX - 首页 */
  INDEX = 1,
  /** CATEGORY - 分类页 */
  CATEGORY = 2,
}

/** 轮播图类型 */
export enum ShopBannerType {
  UNKNOWN_SBT = 0,
  /** GOODS_DETAIL - 商品详情 */
  GOODS_DETAIL = 1,
  /** CATEGORY_DETAIL - 分类详情 */
  CATEGORY_DETAIL = 2,
  /** WEB_VIEW - H5链接 */
  WEB_VIEW = 3,
  /** MINI - 其他小程序 */
  MINI = 4,
}

/** 支付对账单状态 */
export enum PayBillStatus {
  UNKNOWN_PBS = 0,
  /** NO_COMPARE - 未比对 */
  NO_COMPARE = 1,
  /** NO_ERROR - 无误差 */
  NO_ERROR = 2,
  /** HAS_ERROR - 有误差 */
  HAS_ERROR = 3,
}
