// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: common/error.proto

/* eslint-disable */

export enum ErrorReason {
  /** METHOD_NOT_ALLOWED - common error */
  METHOD_NOT_ALLOWED = 0,
  /** REQUEST_TIMEOUT - 408 */
  REQUEST_TIMEOUT = 1,
  /** INTERNAL_SERVER_ERROR - 500 */
  INTERNAL_SERVER_ERROR = 2,
  /** NOT_IMPLEMENTED - 501 */
  NOT_IMPLEMENTED = 3,
  /** NETWORK_ERROR - 502 */
  NETWORK_ERROR = 4,
  /** SERVICE_UNAVAILABLE - 503 */
  SERVICE_UNAVAILABLE = 5,
  /** NETWORK_TIMEOUT - 504 */
  NETWORK_TIMEOUT = 6,
  /** REQUEST_NOT_SUPPORT - 505 */
  REQUEST_NOT_SUPPORT = 7,
  /** BAD_REQUEST - 400 */
  BAD_REQUEST = 100,
  /** INVALID_GRANT_TYPE - 400 */
  INVALID_GRANT_TYPE = 101,
  /** INVALID_USERID - 用户ID无效 */
  INVALID_USERID = 102,
  /** INVALID_TOKEN - token无效 */
  INVALID_TOKEN = 103,
  /** INVALID_PASSWORD - 密码无效 */
  INVALID_PASSWORD = 104,
  /** RESOURCE_NOT_FOUND - 404 */
  RESOURCE_NOT_FOUND = 200,
  /** USER_NOT_FOUND - 用户不存在 */
  USER_NOT_FOUND = 201,
  /** NOT_LOGGED_IN - 401 */
  NOT_LOGGED_IN = 300,
  /** USER_FREEZE - 用户被冻结 */
  USER_FREEZE = 301,
  /** INCORRECT_PASSWORD - 密码错误 */
  INCORRECT_PASSWORD = 302,
  /** INCORRECT_APP_SECRET - 密钥错误 */
  INCORRECT_APP_SECRET = 303,
  /** INCORRECT_ACCESS_TOKEN - 访问令牌错误 */
  INCORRECT_ACCESS_TOKEN = 304,
  /** INCORRECT_REFRESH_TOKEN - 刷新令牌错误 */
  INCORRECT_REFRESH_TOKEN = 305,
  /** TOKEN_EXPIRED - token过期 */
  TOKEN_EXPIRED = 306,
  /** TOKEN_NOT_EXIST - token不存在 */
  TOKEN_NOT_EXIST = 307,
  /** ACCESS_FORBIDDEN - 403 */
  ACCESS_FORBIDDEN = 400,
}
