// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_api.proto

/* eslint-disable */
import { type Empty } from "../google/protobuf/empty";

export interface ListBaseApiResponse {
  /** 分页数据 */
  list: BaseApi[];
}

/** 日志 */
export interface BaseApi {
  /** API ID */
  id: number;
  /** 服务名 */
  serviceName: string;
  /** 服务描述 */
  serviceDesc: string;
  /** 描述 */
  desc: string;
  /** 操作方法 */
  operation: string;
  /** 请求方法 */
  method: string;
  /** 请求地址 */
  path: string;
}

/** AdminAPI服务 */
export interface BaseApiService {
  /** 查询API列表 */
  ListBaseApi(request: Empty): Promise<ListBaseApiResponse>;
}
