// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_role.proto

/* eslint-disable */
import { type SelectOptionResponse, type SetStatusRequest } from "../common/common";
import { type BaseRoleDataScope, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageBaseRoleRequest {
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseRoleResponse {
  /** 分页数据 */
  list: BaseRole[];
  /** 总数 */
  total: number;
}

/** 角色 */
export interface BaseRole {
  /** 角色ID */
  id: number;
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 数据权限：0全部数据1部门及子部门数据2本部门数据3本人数据 */
  dataScope: BaseRoleDataScope;
  /** 分配的菜单列表 */
  menus: number[];
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 角色 */
export interface BaseRoleForm {
  /** 角色ID */
  id: number;
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 数据权限：0全部数据1部门及子部门数据2本部门数据3本人数据 */
  dataScope?:
    | BaseRoleDataScope
    | undefined;
  /** 分配的菜单列表 */
  menus: number[];
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 备注 */
  remark: string;
}

export interface SetMenusRequest {
  /** 用户ID */
  id: number;
  /** 分配的菜单列表 */
  menus: number[];
}

/** Admin角色管理服务 */
export interface BaseRoleService {
  /** 查询角色下拉选择 */
  OptionBaseRole(request: Empty): Promise<SelectOptionResponse>;
  /** 查询角色分页列表 */
  PageBaseRole(request: PageBaseRoleRequest): Promise<PageBaseRoleResponse>;
  /** 查询角色 */
  GetBaseRole(request: Int64Value): Promise<BaseRoleForm>;
  /** 创建角色 */
  CreateBaseRole(request: BaseRoleForm): Promise<Empty>;
  /** 更新角色 */
  UpdateBaseRole(request: BaseRoleForm): Promise<Empty>;
  /** 删除角色 */
  DeleteBaseRole(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseRoleStatus(request: SetStatusRequest): Promise<Empty>;
  /** 设置角色菜单权限 */
  SetBaseRoleMenus(request: SetMenusRequest): Promise<Empty>;
}
