// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_menu.proto

/* eslint-disable */
import { type SetStatusRequest, type TreeOptionResponse } from "../common/common";
import { type BaseMenuType, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface TreeBaseMenuResponse {
  list: BaseMenu[];
}

export interface OptionBaseMenuRequest {
  /** 父级菜单ID */
  parentId?: number | undefined;
}

/** 菜单 */
export interface BaseMenu {
  /** 菜单ID */
  id: number;
  /** 父级菜单ID */
  parentId: number;
  /** 菜单类型 */
  type: BaseMenuType;
  /** 路由地址 */
  path: string;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name: string;
  /** 组件路径 */
  component: string;
  /** 重定向地址 */
  redirect: string;
  /** 路由元信息 */
  meta:
    | BaseMenuMeta
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 子菜单 */
  children: BaseMenu[];
}

/** 菜单 */
export interface BaseMenuForm {
  /** 菜单ID */
  id: number;
  /** 父级菜单ID */
  parentId?:
    | number
    | undefined;
  /** 菜单类型 */
  type?:
    | BaseMenuType
    | undefined;
  /** 路由地址 */
  path: string;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name: string;
  /** 组件路径 */
  component: string;
  /** 重定向地址 */
  redirect: string;
  /** 路由元信息 */
  meta:
    | BaseMenuMeta
    | undefined;
  /** 分配的API列表 */
  apis: string[];
  /** 排序 */
  sort: number;
  /** 状态 */
  status?: Status | undefined;
}

export interface BaseMenuMeta {
  /** 菜单标题 */
  title: string;
  /** 菜单图标 */
  icon?:
    | string
    | undefined;
  /** 【目录】只有一个子路由是否始终显示 */
  alwaysShow?:
    | boolean
    | undefined;
  /** 是否隐藏(true-是 false-否) */
  hidden?:
    | boolean
    | undefined;
  /** 参数 */
  keepAlive?:
    | boolean
    | undefined;
  /** 参数 */
  params: BaseMenuParams[];
}

export interface BaseMenuParams {
  /** key */
  key: string;
  /** value */
  value: string;
}

/** Admin菜单管理服务 */
export interface BaseMenuService {
  /** 查询菜单树形列表 */
  TreeBaseMenu(request: Empty): Promise<TreeBaseMenuResponse>;
  /** 查询菜单树形选择 */
  OptionBaseMenu(request: OptionBaseMenuRequest): Promise<TreeOptionResponse>;
  /** 查询菜单 */
  GetBaseMenu(request: Int64Value): Promise<BaseMenuForm>;
  /** 创建菜单 */
  CreateBaseMenu(request: BaseMenuForm): Promise<Empty>;
  /** 更新菜单 */
  UpdateBaseMenu(request: BaseMenuForm): Promise<Empty>;
  /** 删除菜单 */
  DeleteBaseMenu(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseMenuStatus(request: SetStatusRequest): Promise<Empty>;
}
