// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_dept.proto

/* eslint-disable */
import { type SetStatusRequest, type TreeOptionResponse } from "../common/common";
import { type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface TreeBaseDeptResponse {
  /** 分页数据 */
  list: BaseDept[];
}

export interface OptionBaseDeptRequest {
  /** 父级部门ID */
  parentId?: number | undefined;
}

/** 部门 */
export interface BaseDept {
  /** 部门ID */
  id: number;
  /** 父级部门ID */
  parentId: number;
  /** 部门名称 */
  name: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 子部门 */
  children: BaseDept[];
}

/** 部门 */
export interface BaseDeptForm {
  /** 部门ID */
  id: number;
  /** 父级部门ID */
  parentId?:
    | number
    | undefined;
  /** 部门名称 */
  name: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 备注 */
  remark: string;
}

/** Admin部门服务 */
export interface BaseDeptService {
  /** 查询部门树形列表 */
  TreeBaseDept(request: Empty): Promise<TreeBaseDeptResponse>;
  /** 查询部门树形选择 */
  OptionBaseDept(request: OptionBaseDeptRequest): Promise<TreeOptionResponse>;
  /** 查询部门 */
  GetBaseDept(request: Int64Value): Promise<BaseDeptForm>;
  /** 创建部门 */
  CreateBaseDept(request: BaseDeptForm): Promise<Empty>;
  /** 更新部门 */
  UpdateBaseDept(request: BaseDeptForm): Promise<Empty>;
  /** 删除部门 */
  DeleteBaseDept(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseDeptStatus(request: SetStatusRequest): Promise<Empty>;
}
