// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_log.proto

/* eslint-disable */
import { type Int64Value } from "../google/protobuf/wrappers";

export interface PageBaseLogRequest {
  /** 请求时间 */
  requestTime: string[];
  /** 操作方法 */
  operation: string;
  /** 状态码 */
  statusCode?:
    | number
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseLogResponse {
  /** 分页数据 */
  list: BaseLog[];
  /** 总数 */
  total: number;
}

/** 日志 */
export interface BaseLog {
  /** 日志ID */
  id: number;
  /** 请求ID */
  requestId: string;
  /** 请求ID */
  requestTime: string;
  /** 请求方法 */
  method: string;
  /** 操作方法 */
  operation: string;
  /** 请求路径 */
  path: string;
  /** 请求源 */
  referer: string;
  /** 请求URI */
  requestUri: string;
  /** 请求头 */
  requestHeader: string;
  /** 请求体 */
  requestBody: string;
  /** 响应信息 */
  response: string;
  /** 操作耗时 */
  costTime: string;
  /** 操作是否成功 */
  success: boolean;
  /** 状态码 */
  statusCode: number;
  /** 操作失败原因 */
  reason: string;
  /** 操作地理位置 */
  location: string;
  /** 操作者用户ID */
  userId: number;
  /** 操作者账号名 */
  userName: string;
  /** 操作者IP */
  clientIp: string;
  /** 浏览器的用户代理信息 */
  userAgent: string;
  /** 浏览器名称 */
  browserName: string;
  /** 浏览器版本 */
  browserVersion: string;
  /** 客户端ID */
  clientId: string;
  /** 客户端名称 */
  clientName: string;
  /** 操作系统名称 */
  osName: string;
  /** 操作系统版本 */
  osVersion: string;
}

/** Admin日志服务 */
export interface BaseLogService {
  /** 查询日志分页列表 */
  PageBaseLog(request: PageBaseLogRequest): Promise<PageBaseLogResponse>;
  /** 查询日志 */
  GetBaseLog(request: Int64Value): Promise<BaseLog>;
}
