// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_dict.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageBaseDictRequest {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseDictResponse {
  /** 分页数据 */
  list: BaseDict[];
  /** 总数 */
  total: number;
}

/** 字典 */
export interface BaseDict {
  /** 字典ID */
  id: number;
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 字典 */
export interface BaseDictForm {
  /** 字典ID */
  id: number;
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 状态 */
  status?: Status | undefined;
}

export interface PageBaseDictItemRequest {
  /** 字典id */
  dictId: number;
  /** 字典属性名称 */
  label: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseDictItemResponse {
  /** 分页数据 */
  list: BaseDictItem[];
  /** 总数 */
  total: number;
}

export interface ListBaseDictResponse {
  /** 分页数据 */
  list: ListBaseDictResponse_BaseDict[];
}

export interface ListBaseDictResponse_BaseDictItem {
  /** 字典值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tagType: string;
}

export interface ListBaseDictResponse_BaseDict {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 字典属性 */
  items: ListBaseDictResponse_BaseDictItem[];
}

export interface BaseDictItem {
  /** 字典ID */
  id: number;
  /** 字典ID */
  dictId: number;
  /** 字典值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tagType: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

export interface BaseDictItemForm {
  /** 字典ID */
  id: number;
  /** 字典ID */
  dictId: number;
  /** 字典值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tagType: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status?: Status | undefined;
}

/** Admin字典服务 */
export interface BaseDictService {
  /** 查询字典列表 */
  ListBaseDict(request: Empty): Promise<ListBaseDictResponse>;
  /** 查询字典分页列表 */
  PageBaseDict(request: PageBaseDictRequest): Promise<PageBaseDictResponse>;
  /** 查询字典 */
  GetBaseDict(request: Int64Value): Promise<BaseDictForm>;
  /** 创建字典 */
  CreateBaseDict(request: BaseDictForm): Promise<Empty>;
  /** 更新字典 */
  UpdateBaseDict(request: BaseDictForm): Promise<Empty>;
  /** 删除字典 */
  DeleteBaseDict(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseDictStatus(request: SetStatusRequest): Promise<Empty>;
  /** 查询字典属性分页列表 */
  PageBaseDictItem(request: PageBaseDictItemRequest): Promise<PageBaseDictItemResponse>;
  /** 查询字典属性 */
  GetBaseDictItem(request: Int64Value): Promise<BaseDictItemForm>;
  /** 创建字典属性 */
  CreateBaseDictItem(request: BaseDictItemForm): Promise<Empty>;
  /** 更新字典属性 */
  UpdateBaseDictItem(request: BaseDictItemForm): Promise<Empty>;
  /** 删除字典属性 */
  DeleteBaseDictItem(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseDictItemStatus(request: SetStatusRequest): Promise<Empty>;
}
