// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_user.proto

/* eslint-disable */
import { type SelectOptionResponse, type SetStatusRequest } from "../common/common";
import { type BaseUserGender, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

/** 用户编号 */
export enum BaseUserName {
  USER_NAME_UNSPECIFIED = 0,
  /** super - 超级管理员 */
  super = 1,
}

export interface OptionBaseUserRequest {
  /** 关键字 */
  keyword: string;
}

export interface PageBaseUserRequest {
  /** 用户账号 */
  userName: string;
  /** 用户昵称 */
  nickName: string;
  /** 部门ID */
  deptId?:
    | number
    | undefined;
  /** 手机号 */
  phone: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseUserResponse {
  /** 分页数据 */
  list: BaseUser[];
  /** 总数 */
  total: number;
}

/** 用户 */
export interface BaseUser {
  /** 用户ID */
  id: number;
  /** 用户账号 */
  userName: string;
  /** 用户昵称 */
  nickName: string;
  /** 角色ID */
  roleId: number;
  /** 部门ID */
  deptId: number;
  /** 手机号 */
  phone: string;
  /** 性别 */
  gender: BaseUserGender;
  /** 头像 */
  avatar: string;
  /** 用户状态 */
  status: Status;
  /** 备注名 */
  remark: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 用户 */
export interface BaseUserForm {
  /** 用户ID */
  id: number;
  /** 用户账号 */
  userName: string;
  /** 用户昵称 */
  nickName: string;
  /** 角色ID */
  roleId?:
    | number
    | undefined;
  /** 部门ID */
  deptId?:
    | number
    | undefined;
  /** 手机号 */
  phone: string;
  /** 密码 */
  pwd: string;
  /** 性别 */
  gender?:
    | BaseUserGender
    | undefined;
  /** 头像 */
  avatar: string;
  /** 用户状态 */
  status?:
    | Status
    | undefined;
  /** 备注名 */
  remark: string;
}

export interface ResetBaseUserPwdRequest {
  /** 用户ID */
  id: number;
  /** 密码 */
  pwd: string;
}

/** Admin用户管理服务 */
export interface BaseUserService {
  /** 查询用户下拉选择 */
  OptionBaseUser(request: OptionBaseUserRequest): Promise<SelectOptionResponse>;
  /** 查询用户分页列表 */
  PageBaseUser(request: PageBaseUserRequest): Promise<PageBaseUserResponse>;
  /** 查询用户 */
  GetBaseUser(request: Int64Value): Promise<BaseUserForm>;
  /** 创建用户 */
  CreateBaseUser(request: BaseUserForm): Promise<Empty>;
  /** 更新用户 */
  UpdateBaseUser(request: BaseUserForm): Promise<Empty>;
  /** 删除用户 */
  DeleteBaseUser(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseUserStatus(request: SetStatusRequest): Promise<Empty>;
  /** 重置密码 */
  ResetBaseUserPwd(request: ResetBaseUserPwdRequest): Promise<Empty>;
}
