// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_config.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type BaseConfigSite, type BaseConfigType, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageBaseConfigRequest {
  /** 位置：枚举【BaseConfigSite】 */
  site?:
    | BaseConfigSite
    | undefined;
  /** 配置名称 */
  name?:
    | string
    | undefined;
  /** 配置类型：枚举【BaseConfigType】 */
  type?:
    | BaseConfigType
    | undefined;
  /** 配置key */
  key?:
    | string
    | undefined;
  /** 状态：枚举【Status】 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseConfigResponse {
  /** 分页数据 */
  list: BaseConfig[];
  /** 总数 */
  total: number;
}

export interface BaseConfig {
  /** 配置ID */
  id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
  /** 配置名称 */
  name: string;
  /** 配置类型：枚举【BaseConfigType】 */
  type: BaseConfigType;
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
  /** 状态：枚举【Status】 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

export interface BaseConfigForm {
  /** 配置ID */
  id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site?:
    | BaseConfigSite
    | undefined;
  /** 配置名称 */
  name: string;
  /** 配置类型：1、文本，2、图片。3、富文本 */
  type?:
    | BaseConfigType
    | undefined;
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
  /** 状态 */
  status?: Status | undefined;
}

/** Admin系统配置服务 */
export interface BaseConfigService {
  /** 刷新缓存 */
  RefreshBaseConfig(request: Empty): Promise<Empty>;
  /** 查询系统配置分页列表 */
  PageBaseConfig(request: PageBaseConfigRequest): Promise<PageBaseConfigResponse>;
  /** 查询系统配置 */
  GetBaseConfig(request: Int64Value): Promise<BaseConfigForm>;
  /** 创建系统配置 */
  CreateBaseConfig(request: BaseConfigForm): Promise<Empty>;
  /** 更新系统配置 */
  UpdateBaseConfig(request: BaseConfigForm): Promise<Empty>;
  /** 删除系统配置 */
  DeleteBaseConfig(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseConfigStatus(request: SetStatusRequest): Promise<Empty>;
}
