// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/base_job.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type BaseJobLogStatus, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageBaseJobRequest {
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invokeTarget: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseJobResponse {
  /** 分页数据 */
  list: BaseJob[];
  /** 总数 */
  total: number;
}

export interface StartBaseJobRequest {
  /** 主键id */
  id: number;
}

export interface StopBaseJobRequest {
  /** 主键id */
  id: number;
}

export interface ExecBaseJobRequest {
  /** 主键id */
  id: number;
}

export interface BaseJobArgs {
  /** 参数 */
  key: string;
  /** 值 */
  value: string;
}

/** 定时任务 */
export interface BaseJob {
  /** 任务ID */
  id: number;
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invokeTarget: string;
  /** 目标参数 */
  args: BaseJobArgs[];
  /** cron表达式 */
  cronExpression: string;
  /** job启动时返回的id */
  entryId: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 定时任务 */
export interface BaseJobForm {
  /** 任务ID */
  id: number;
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invokeTarget: string;
  /** 目标参数 */
  args: BaseJobArgs[];
  /** cron表达式 */
  cronExpression: string;
  status?: Status | undefined;
}

export interface PageBaseJobLogRequest {
  /** 任务id */
  jobId: number;
  /** 状态 */
  status?:
    | BaseJobLogStatus
    | undefined;
  /** 执行时间 */
  executeTime: string[];
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageBaseJobLogResponse {
  /** 分页数据 */
  list: BaseJobLog[];
  /** 总数 */
  total: number;
}

/** 定时任务日志 */
export interface BaseJobLog {
  /** 任务日志ID */
  id: number;
  /** 任务ID */
  jobId: number;
  /** 执行参数 */
  input: string;
  /** 输出结果 */
  output: string;
  /** 错误信息 */
  error: string;
  /** 状态：1、成功。2、失败。 */
  status: BaseJobLogStatus;
  /** 消耗时间/毫秒 */
  processTime: string;
  /** 执行时间 */
  executeTime: string;
}

/** Admin定时任务服务 */
export interface BaseJobService {
  /** 查询定时任务分页列表 */
  PageBaseJob(request: PageBaseJobRequest): Promise<PageBaseJobResponse>;
  /** 查询定时任务 */
  GetBaseJob(request: Int64Value): Promise<BaseJobForm>;
  /** 创建定时任务 */
  CreateBaseJob(request: BaseJobForm): Promise<Empty>;
  /** 更新定时任务 */
  UpdateBaseJob(request: BaseJobForm): Promise<Empty>;
  /** 删除定时任务 */
  DeleteBaseJob(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetBaseJobStatus(request: SetStatusRequest): Promise<Empty>;
  /** 启动任务 */
  StartBaseJob(request: StartBaseJobRequest): Promise<Empty>;
  /** 停止任务 */
  StopBaseJob(request: StopBaseJobRequest): Promise<Empty>;
  /** 执行任务 */
  ExecBaseJob(request: ExecBaseJobRequest): Promise<Empty>;
  /** 查询定时任务日志分页列表 */
  PageBaseJobLog(request: PageBaseJobLogRequest): Promise<PageBaseJobLogResponse>;
  /** 查询定时任务日志 */
  GetBaseJobLog(request: Int64Value): Promise<BaseJobLog>;
}
