// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/dashboard.proto

/* eslint-disable */

/** 时间类型 */
export enum DashboardTimeType {
  /** DAY - 日 */
  DAY = 0,
  /** WEEK - 周 */
  WEEK = 1,
  /** MONTH - 月 */
  MONTH = 2,
}

/** 汇总数据请求参数 */
export interface DashboardCountRequest {
  /** 时间类型 */
  timeType: DashboardTimeType;
}

/** 汇总数据返回结果 */
export interface DashboardCountResponse {
  /** 新增数量 */
  newNum: number;
  /** 总数量 */
  totalNum: number;
}

/** 订单销量（柱状图）请求参数 */
export interface DashboardBarOrderRequest {
  /** 时间类型 */
  timeType: DashboardTimeType;
}

/** 商品销量（柱状图）请求参数 */
export interface DashboardBarGoodsRequest {
  /** 时间类型 */
  timeType: DashboardTimeType;
  /** top */
  top: number;
}

/** 商品分类（饼状图）请求参数 */
export interface DashboardPieGoodsRequest {
  /** 时间类型 */
  timeType: DashboardTimeType;
}

/** 商品订单销量状态（雷达图）请求参数 */
export interface DashboardRadarOrderRequest {
  /** 时间类型 */
  timeType: DashboardTimeType;
}

/** （柱状图）请求参数 */
export interface DashboardBarResponse {
  /** 图例的数据数组 */
  axisData: string[];
  /** 数据内容数组 */
  seriesData: DashboardBarResponse_SeriesData[];
}

export interface DashboardBarResponse_SeriesData {
  /** 数量 */
  value: number[];
}

/** （饼状图）返回结果 */
export interface DashboardPieResponse {
  /** 数据内容数组 */
  seriesData: DashboardPieResponse_SeriesData[];
}

export interface DashboardPieResponse_SeriesData {
  /** 数值 */
  value: number;
  /** 系列名称 */
  name: string;
}

/** （雷达图）返回结果 */
export interface DashboardRadarResponse {
  /** 图例的数据数组 */
  legendData: string[];
  /** 指示器 */
  radarIndicator: DashboardRadarResponse_RadarIndicator[];
  /** 数据 */
  seriesData: DashboardRadarResponse_SeriesData[];
}

export interface DashboardRadarResponse_RadarIndicator {
  /** 指示器名称 */
  name: string;
}

export interface DashboardRadarResponse_SeriesData {
  /** 数据项名称 */
  name: string;
  /** 单个数据项的数值 */
  value: number[];
}

/** Admin首页服务 */
export interface DashboardService {
  /** 查询汇总数据（用户） */
  DashboardCountUser(request: DashboardCountRequest): Promise<DashboardCountResponse>;
  /** 查询汇总数据（商品） */
  DashboardCountGoods(request: DashboardCountRequest): Promise<DashboardCountResponse>;
  /** 查询汇总数据（订单） */
  DashboardCountOrder(request: DashboardCountRequest): Promise<DashboardCountResponse>;
  /** 查询汇总数据（销量） */
  DashboardCountSale(request: DashboardCountRequest): Promise<DashboardCountResponse>;
  /** 查询订单销量（柱状图） */
  DashboardBarOrder(request: DashboardBarOrderRequest): Promise<DashboardBarResponse>;
  /** 查询商品销量（柱状图） */
  DashboardBarGoods(request: DashboardBarGoodsRequest): Promise<DashboardBarResponse>;
  /** 查询商品分类（饼状图） */
  DashboardPieGoods(request: DashboardPieGoodsRequest): Promise<DashboardPieResponse>;
  /** 查询商品订单销量状态（雷达图） */
  DashboardRadarOrder(request: DashboardRadarOrderRequest): Promise<DashboardRadarResponse>;
}
