// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/goods_prop.proto

/* eslint-disable */
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageGoodsPropRequest {
  /** 商品id */
  goodsId: number;
  /** 商品属性名称 */
  label: string;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageGoodsPropResponse {
  /** 分页数据 */
  list: GoodsProp[];
  /** 总数 */
  total: number;
}

export interface GoodsProp {
  /** 商品属性ID */
  id: number;
  /** 商品id */
  goodsId: number;
  /** 商品属性名称 */
  label: string;
  /** 商品属性value */
  value: string;
  /** 排序 */
  sort: number;
}

/** Admin商品属性服务 */
export interface GoodsPropService {
  /** 查询商品属性分页列表 */
  PageGoodsProp(request: PageGoodsPropRequest): Promise<PageGoodsPropResponse>;
  /** 查询商品属性 */
  GetGoodsProp(request: Int64Value): Promise<GoodsProp>;
  /** 创建商品属性 */
  CreateGoodsProp(request: GoodsProp): Promise<Empty>;
  /** 更新商品属性 */
  UpdateGoodsProp(request: GoodsProp): Promise<Empty>;
  /** 删除商品属性 */
  DeleteGoodsProp(request: StringValue): Promise<Empty>;
}
