// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/goods.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type GoodsStatus } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";
import { type GoodsProp } from "./goods_prop";
import { type GoodsSku } from "./goods_sku";
import { type GoodsSpec } from "./goods_spec";

export interface ListGoodsRequest {
  /** 商品名称 */
  name: string;
}

export interface ListGoodsResponse {
  /** 分页数据 */
  list: ListGoodsResponse_Goods[];
}

export interface ListGoodsResponse_Goods {
  /** 商品ID */
  id: number;
  /** 名称 */
  name: string;
  /** 当前价格(分) */
  price: number;
  /** 分类名称 */
  categoryName: string;
}

export interface PageGoodsRequest {
  /** 分类id */
  categoryId?:
    | number
    | undefined;
  /** 商品名称 */
  name: string;
  /** 状态 */
  status?:
    | GoodsStatus
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageGoodsResponse {
  /** 分页数据 */
  list: Goods[];
  /** 总数 */
  total: number;
}

export interface Goods {
  /** 商品ID */
  id: number;
  /** 分类ID */
  categoryId: number;
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 当前价格(分) */
  price: number;
  /** 折扣价格（分） */
  discountPrice: number;
  /** 初始销量 */
  initSaleNum: number;
  /** 真实销售数量 */
  realSaleNum: number;
  /** 状态 */
  status: GoodsStatus;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 分类名称 */
  categoryName: string;
}

export interface GoodsForm {
  /** 商品ID */
  id: number;
  /** 分类ID */
  categoryId?:
    | number
    | undefined;
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 轮播图 */
  banner: string[];
  /** 商品详情 */
  detail: string[];
  /** 状态 */
  status?:
    | GoodsStatus
    | undefined;
  /** 商品属性 */
  propList: GoodsProp[];
  /** 商品SKU */
  skuList: GoodsSku[];
  /** 商品规格 */
  specList: GoodsSpec[];
  /** 分类名称 */
  categoryName: string;
}

/** Admin商品服务 */
export interface GoodsService {
  /** 查询商品列表 */
  ListGoods(request: ListGoodsRequest): Promise<ListGoodsResponse>;
  /** 查询商品分页列表 */
  PageGoods(request: PageGoodsRequest): Promise<PageGoodsResponse>;
  /** 查询商品 */
  GetGoods(request: Int64Value): Promise<GoodsForm>;
  /** 创建商品 */
  CreateGoods(request: GoodsForm): Promise<Empty>;
  /** 更新商品 */
  UpdateGoods(request: GoodsForm): Promise<Empty>;
  /** 删除商品 */
  DeleteGoods(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetGoodsStatus(request: SetStatusRequest): Promise<Empty>;
}
