// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/goods_spec.proto

/* eslint-disable */

export interface ListGoodsSpecRequest {
  /** 商品id */
  goodsId: number;
}

export interface ListGoodsSpecResponse {
  /** 分页数据 */
  list: GoodsSpec[];
}

export interface GoodsSpec {
  /** 商品规格ID */
  id: number;
  /** 商品id */
  goodsId: number;
  /** 商品规格名称 */
  name: string;
  /** 商品规格内容 */
  item: string[];
  /** 排序 */
  sort: number;
}

/** Admin商品规格服务 */
export interface GoodsSpecService {
  /** 查询商品规格列表 */
  ListGoodsSpec(request: ListGoodsSpecRequest): Promise<ListGoodsSpecResponse>;
}
