// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/goods_sku.proto

/* eslint-disable */
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value } from "../google/protobuf/wrappers";

export interface PageGoodsSkuRequest {
  /** 商品id */
  goodsId: number;
  skuCode: string;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageGoodsSkuResponse {
  /** 分页数据 */
  list: GoodsSku[];
  /** 总数 */
  total: number;
}

export interface GoodsSku {
  /** 商品SKUID */
  id: number;
  /** 商品id */
  goodsId: number;
  /** 商品图片 */
  picture: string;
  /** SKU SKU组成，需要与 goods_spec 数组顺序对应 */
  specItem: string[];
  /** SKU编码 */
  skuCode: string;
  /** 当前价格(分) */
  price: number;
  /** 折扣价格（分） */
  discountPrice: number;
  /** 初始销量 */
  initSaleNum: number;
  /** 真实销售数量 */
  realSaleNum: number;
  /** 库存数量 */
  inventory: number;
}

/** Admin商品SKU服务 */
export interface GoodsSkuService {
  /** 查询商品SKU分页列表 */
  PageGoodsSku(request: PageGoodsSkuRequest): Promise<PageGoodsSkuResponse>;
  /** 查询商品SKU */
  GetGoodsSku(request: Int64Value): Promise<GoodsSku>;
  /** 更新商品SKU */
  UpdateGoodsSku(request: GoodsSku): Promise<Empty>;
}
