// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/goods_category.proto

/* eslint-disable */
import { type SetStatusRequest, type TreeOptionResponse } from "../common/common";
import { type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface TreeGoodsCategoryResponse {
  /** 分页数据 */
  list: GoodsCategory[];
}

export interface OptionGoodsCategoryRequest {
  /** 父级分类ID */
  parentId?: number | undefined;
}

/** 分类 */
export interface GoodsCategory {
  /** 分类ID */
  id: number;
  /** 父级分类ID */
  parentId: number;
  /** 分类名称 */
  name: string;
  /** 分类图片 */
  picture: string;
  /** 排序 */
  sort: number;
  /** 菜单状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 子节点树 */
  children: GoodsCategory[];
}

/** 分类 */
export interface GoodsCategoryForm {
  /** 分类ID */
  id: number;
  /** 父级分类ID */
  parentId?:
    | number
    | undefined;
  /** 分类名称 */
  name: string;
  /** 分类图片 */
  picture: string;
  /** 排序 */
  sort: number;
  /** 菜单状态 */
  status?: Status | undefined;
}

/** Admin分类服务 */
export interface GoodsCategoryService {
  /** 查询分类树形列表 */
  TreeGoodsCategory(request: Empty): Promise<TreeGoodsCategoryResponse>;
  /** 查询分类树形选择 */
  OptionGoodsCategory(request: OptionGoodsCategoryRequest): Promise<TreeOptionResponse>;
  /** 查询分类 */
  GetGoodsCategory(request: Int64Value): Promise<GoodsCategoryForm>;
  /** 创建分类 */
  CreateGoodsCategory(request: GoodsCategoryForm): Promise<Empty>;
  /** 更新分类 */
  UpdateGoodsCategory(request: GoodsCategoryForm): Promise<Empty>;
  /** 删除分类 */
  DeleteGoodsCategory(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetGoodsCategoryStatus(request: SetStatusRequest): Promise<Empty>;
}
