// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/order.proto

/* eslint-disable */
import {
  type OrderBillStatus,
  type OrderCancelReason,
  type OrderDeliveryTime,
  type OrderPayChannel,
  type OrderPayType,
  type OrderRefundReason,
  type OrderStatus,
} from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value } from "../google/protobuf/wrappers";

export interface PageOrderRequest {
  /** 订单编号 */
  orderNo: string;
  /** 用户id */
  userId: number;
  /** 订单状态 */
  status?:
    | OrderStatus
    | undefined;
  /** 支付方式：枚举【OrderPayType】 */
  payType?:
    | OrderPayType
    | undefined;
  /** 支付渠道：枚举【OrderPayChannel】 */
  payChannel?:
    | OrderPayChannel
    | undefined;
  /** 创建时间 */
  createdAt: string[];
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageOrderResponse {
  /** 分页数据 */
  list: Order[];
  /** 总数 */
  total: number;
}

export interface OrderResponse {
  /** 订单信息 */
  order:
    | Order
    | undefined;
  /** 支付倒计时 */
  countdown: number;
  /** 地址信息 */
  address:
    | OrderAddress
    | undefined;
  /** 取消信息 */
  cancel:
    | OrderCancel
    | undefined;
  /** 商品信息 */
  goods: OrderGoods[];
  /** 物流信息 */
  logistics:
    | OrderLogistics
    | undefined;
  /** 支付信息 */
  payment:
    | OrderPayment
    | undefined;
  /** 退款信息 */
  refund: OrderRefund[];
}

export interface OrderRefundResponse {
  /** 支付信息 */
  payment:
    | OrderPayment
    | undefined;
  /** 退款信息 */
  refund: OrderRefund[];
}

export interface RefundOrderRequest {
  /** 订单id */
  orderId: number;
  /** 退款原因：枚举【OrderRefundReason】 */
  reason?:
    | OrderRefundReason
    | undefined;
  /** 退款金额 */
  refundMoney: number;
}

export interface OrderShippedResponse {
  /** 地址信息 */
  address:
    | OrderAddress
    | undefined;
  /** 商品信息 */
  goods: OrderGoods[];
  /** 物流信息 */
  logistics: OrderLogistics | undefined;
}

export interface ShippedOrderRequest {
  /** 订单id */
  orderId: number;
  /** 物流公司名 */
  name: string;
  /** 物流单号 */
  no: string;
  /** 联系方式 */
  contact: string;
}

/** 订单信息表 */
export interface Order {
  /** 订单ID */
  id: number;
  /** 订单编号 */
  orderNo: string;
  /** 用户ID */
  userId: number;
  /** 实际支付金额（单位：分） */
  payMoney: number;
  /** 总价（单位：分） */
  totalMoney: number;
  /** 优惠金额（单位：分） */
  postFee: number;
  /** 商品总数 */
  goodsNum: number;
  /** 支付方式：枚举【OrderPayType】 */
  payType: OrderPayType;
  /** 支付渠道：枚举【OrderPayChannel】 */
  payChannel: OrderPayChannel;
  /** 配送时间：枚举【OrderDeliveryTime】 */
  deliveryTime: OrderDeliveryTime;
  /** 状态：枚举【OrderStatus】 */
  status: OrderStatus;
  /** 订单备注 */
  remark: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 用户名 */
  nickName: string;
}

/** 订单地址信息 */
export interface OrderAddress {
  /** 联系人 */
  receiver: string;
  /** 联系方式 */
  contact: string;
  /** 省市区（JSON存储） */
  address: string[];
  /** 详细地址 */
  detail: string;
}

/** 订单取消信息 */
export interface OrderCancel {
  /** 取消原因：枚举【OrderCancelReason】 */
  reason: OrderCancelReason;
  /** 创建时间 */
  createdAt: string;
}

/** 订单商品信息 */
export interface OrderGoods {
  /** 商品ID */
  goodsId: number;
  /** 规格编号 */
  skuCode: string;
  /** SKU规格组成（需与goods_spec顺序对应，JSON存储） */
  specItem: string[];
  /** 商品图片 */
  picture: string;
  /** 商品名称 */
  name: string;
  /** 数量 */
  num: number;
  /** 当前价格（单位：分） */
  price: number;
  /** 支付价格（单位：分） */
  payPrice: number;
  /** 当前金额汇总 */
  totalPrice: number;
  /** 支付金额汇总 */
  totalPayPrice: number;
}

/** 订单物流信息 */
export interface OrderLogistics {
  /** 物流公司名 */
  name: string;
  /** 物流单号 */
  no: string;
  /** 联系方式 */
  contact: string;
  /** 物流详情（JSON存储） */
  detail: OrderLogistics_Detail[];
  /** 创建时间 */
  createdAt: string;
}

export interface OrderLogistics_Detail {
  /** 时间 */
  time: string;
  /** 动态 */
  text: string;
}

/** 订单支付信息 */
export interface OrderPayment {
  /** 订单编号 */
  orderNo: string;
  /** 三方订单编号 */
  thirdOrderNo: string;
  /** 交易类型 */
  tradeType: string;
  /** 交易状态 */
  tradeState: string;
  /** 交易状态描述 */
  tradeStateDesc: string;
  /** 银行类型 */
  bankType: string;
  /** 支付完成时间 */
  successTime: string;
  /** 支付者信息 */
  payer:
    | OrderPayment_Payer
    | undefined;
  /** 订单金额 */
  amount:
    | OrderPayment_Amount
    | undefined;
  /** 场景信息 */
  sceneInfo:
    | OrderPayment_SceneInfo
    | undefined;
  /** 对账状态：枚举【OrderBillStatus】 */
  status: OrderBillStatus;
}

/** 支付者信息 */
export interface OrderPayment_Payer {
  /** 【用户标识】用户在商户appid下的唯一标识 */
  openid: string;
}

/** 订单金额信息，当支付成功时返回该字段 */
export interface OrderPayment_Amount {
  /** 【用户支付金额】用户支付金额，整型，单位为分。（指使用优惠券的情况下，这里等于总金额-优惠券金额） */
  payerTotal: number;
  /** 【总金额】订单总金额，单位为分，整型 */
  total: number;
  /** 【货币类型】固定返回：CNY，代表人民币 */
  currency: string;
  /** 【用户支付币种】 固定返回：CNY，代表人民币。 */
  payerCurrency: string;
}

/** 场景信息 */
export interface OrderPayment_SceneInfo {
  /** 【商户端设备号】门店号/收银设备ID */
  deviceId: string;
}

/** 订单退款信息 */
export interface OrderRefund {
  /** 支付订单编号 */
  orderNo: string;
  /** 三方支付订单编号 */
  thirdOrderNo: string;
  /** 退款编号 */
  refundNo: string;
  /** 退款原因：枚举【OrderRefundReason】 */
  reason: OrderRefundReason;
  /** 三方退款编号 */
  thirdRefundNo: string;
  /** 退款渠道 */
  channel: string;
  /** 退款入账账户 */
  userReceivedAccount: string;
  /** 退款创建时间 */
  createTime: string;
  /** 退款成功时间 */
  successTime: string;
  /** 退款状态 */
  refundState: string;
  /** 资金账户类型 */
  fundsAccount: string;
  /** 金额信息 */
  amount:
    | OrderRefund_Amount
    | undefined;
  /** 对账状态：枚举【OrderBillStatus】 */
  status: OrderBillStatus;
}

/** 【金额信息】 */
export interface OrderRefund_Amount {
  /** 【原订单金额】单位：分 */
  total: number;
  /** 【退款金额】单位：分 */
  refund: number;
  /** 【用户实际支付金额】单位：分 */
  payerTotal: number;
  /** 【用户退款金额】单位：分 */
  payerRefund: number;
}

/** Admin订单服务 */
export interface OrderService {
  /** 查询订单分页列表 */
  PageOrder(request: PageOrderRequest): Promise<PageOrderResponse>;
  /** 查询订单 */
  GetOrder(request: Int64Value): Promise<OrderResponse>;
  /** 查询订单退款信息 */
  GetOrderRefund(request: Int64Value): Promise<OrderRefundResponse>;
  /** 订单退款 */
  RefundOrder(request: RefundOrderRequest): Promise<Empty>;
  /** 查询订单发货信息 */
  GetOrderShipped(request: Int64Value): Promise<OrderShippedResponse>;
  /** 订单发货 */
  ShippedOrder(request: ShippedOrderRequest): Promise<Empty>;
}
