// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/pay_bill.proto

/* eslint-disable */
import { type PayBillStatus } from "../common/enum";

export interface PagePayBillRequest {
  /** 账单日期 */
  billDate: string;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PagePayBillResponse {
  /** 分页数据 */
  list: PayBill[];
  /** 总数 */
  total: number;
}

/** 支付账单 */
export interface PayBill {
  /** 主键id */
  id: number;
  /** 格式YYYY-MM-DD。仅支持三个月内的账单下载申请 */
  billDate: string;
  /** 账单类型：ALL: 返回当日所有订单信息（不含充值退款订单）SUCCESS:返回当日成功支付的订单（不含充值退款订单）REFUND: 返回当日退款订单（不含充值退款订单） */
  billType: string;
  /** 文件路径 */
  filePath: string;
  /** 哈希类型，固定为SHA1 */
  hashType: string;
  /** 账单文件的SHA1摘要值，用于商户侧校验文件的一致性。 */
  hashValue: string;
  /** 总笔数 */
  totalCount: number;
  /** 总金额,单位：分 */
  totalAmount: number;
  /** 对账文件总笔数 */
  thirdTotalCount: number;
  /** 对账文件总金额，单位：分 */
  thirdTotalAmount: number;
  /** 对账状态：枚举【PayBillStatus】 */
  status: PayBillStatus;
}

/** Admin支付账单服务 */
export interface PayBillService {
  /** 查询支付账单分页列表 */
  PagePayBill(request: PagePayBillRequest): Promise<PagePayBillResponse>;
}
