// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/shop_banner.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type ShopBannerSite, type ShopBannerType, type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageShopBannerRequest {
  /** 位置：枚举【ShopBannerSite】 */
  site?:
    | ShopBannerSite
    | undefined;
  /** 跳转类型：枚举【ShopBannerType】 */
  type?:
    | ShopBannerType
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageShopBannerResponse {
  /** 分页数据 */
  list: ShopBanner[];
  /** 总数 */
  total: number;
}

export interface ShopBanner {
  /** 主键id */
  id: number;
  /** 位置：枚举【ShopBannerSite】 */
  site: ShopBannerSite;
  /** 图片链接 */
  picture: string;
  /** 跳转类型：枚举【ShopBannerType】 */
  type: ShopBannerType;
  /** 跳转地址 */
  href: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

export interface ShopBannerForm {
  /** 主键id */
  id: number;
  /** 位置：枚举【ShopBannerSite】 */
  site?:
    | ShopBannerSite
    | undefined;
  /** 图片链接 */
  picture: string;
  /** 跳转类型：枚举【ShopBannerType】 */
  type?:
    | ShopBannerType
    | undefined;
  /** 跳转地址 */
  href: string;
  /** 排序 */
  sort: number;
  /** 状态：枚举【Status】 */
  status?: Status | undefined;
}

/** Admin轮播图服务 */
export interface ShopBannerService {
  /** 查询轮播图分页列表 */
  PageShopBanner(request: PageShopBannerRequest): Promise<PageShopBannerResponse>;
  /** 查询轮播图 */
  GetShopBanner(request: Int64Value): Promise<ShopBannerForm>;
  /** 创建轮播图 */
  CreateShopBanner(request: ShopBannerForm): Promise<Empty>;
  /** 更新轮播图 */
  UpdateShopBanner(request: ShopBannerForm): Promise<Empty>;
  /** 删除轮播图 */
  DeleteShopBanner(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetShopBannerStatus(request: SetStatusRequest): Promise<Empty>;
}
