// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/shop_service.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageShopServiceRequest {
  /** 标签 */
  label: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageShopServiceResponse {
  /** 分页数据 */
  list: ShopService[];
  /** 总数 */
  total: number;
}

export interface ShopService {
  /** 服务ID */
  id: number;
  /** 标签 */
  label: string;
  /** 值 */
  value: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

export interface ShopServiceForm {
  /** 服务ID */
  id: number;
  /** 标签 */
  label: string;
  /** 值 */
  value: string;
  /** 排序 */
  sort: number;
  /** 状态：枚举【Status】 */
  status?: Status | undefined;
}

/** Admin商城服务 */
export interface ShopServiceService {
  /** 查询商城服务分页列表 */
  PageShopService(request: PageShopServiceRequest): Promise<PageShopServiceResponse>;
  /** 查询商城服务 */
  GetShopService(request: Int64Value): Promise<ShopServiceForm>;
  /** 创建商城服务 */
  CreateShopService(request: ShopServiceForm): Promise<Empty>;
  /** 更新商城服务 */
  UpdateShopService(request: ShopServiceForm): Promise<Empty>;
  /** 删除商城服务 */
  DeleteShopService(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetShopServiceStatus(request: SetStatusRequest): Promise<Empty>;
}
