// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/shop_hot.proto

/* eslint-disable */
import { type SetStatusRequest } from "../common/common";
import { type Status } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value, type StringValue } from "../google/protobuf/wrappers";

export interface PageShopHotRequest {
  /** 商城热门推荐标题 */
  title: string;
  /** 商城热门推荐描述 */
  desc: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageShopHotResponse {
  /** 分页数据 */
  list: ShopHot[];
  /** 总数 */
  total: number;
}

export interface PageShopHotItemRequest {
  /** 商城热门推荐id */
  hotId: number;
  /** 商城热门推荐属性标题 */
  title: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageShopHotItemResponse {
  /** 分页数据 */
  list: ShopHotItem[];
  /** 总数 */
  total: number;
}

/** 商城热门推荐 */
export interface ShopHot {
  /** 商城热门推荐ID */
  id: number;
  /** 商城热门推荐标题 */
  title: string;
  /** 商城热门推荐名称 */
  desc: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 商城热门推荐 */
export interface ShopHotForm {
  /** 商城热门推荐ID */
  id: number;
  /** 商城热门推荐标题 */
  title: string;
  /** 商城热门推荐名称 */
  desc: string;
  /** 轮播图 */
  banner: string;
  /** 图片 */
  picture: string[];
  /** 排序 */
  sort: number;
  /** 状态 */
  status?: Status | undefined;
}

export interface ShopHotItem {
  /** 商城热门推荐ID */
  id: number;
  /** 商城热门推荐ID */
  hotId: number;
  /** 商城热门推荐值 */
  title: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

export interface ShopHotItemForm {
  /** 商城热门推荐ID */
  id: number;
  /** 商城热门推荐ID */
  hotId: number;
  /** 标题 */
  title: string;
  /** 排序 */
  sort: number;
  /** 商品 */
  goodsIds: number[];
  /** 状态：枚举【Status】 */
  status?: Status | undefined;
}

/** Admin商城热门推荐服务 */
export interface ShopHotService {
  /** 查询商城热门推荐分页列表 */
  PageShopHot(request: PageShopHotRequest): Promise<PageShopHotResponse>;
  /** 查询商城热门推荐 */
  GetShopHot(request: Int64Value): Promise<ShopHotForm>;
  /** 创建商城热门推荐 */
  CreateShopHot(request: ShopHotForm): Promise<Empty>;
  /** 更新商城热门推荐 */
  UpdateShopHot(request: ShopHotForm): Promise<Empty>;
  /** 删除商城热门推荐 */
  DeleteShopHot(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetShopHotStatus(request: SetStatusRequest): Promise<Empty>;
  /** 查询商城热门推荐属性分页列表 */
  PageShopHotItem(request: PageShopHotItemRequest): Promise<PageShopHotItemResponse>;
  /** 查询商城热门推荐属性 */
  GetShopHotItem(request: Int64Value): Promise<ShopHotItemForm>;
  /** 创建商城热门推荐属性 */
  CreateShopHotItem(request: ShopHotItemForm): Promise<Empty>;
  /** 更新商城热门推荐属性 */
  UpdateShopHotItem(request: ShopHotItemForm): Promise<Empty>;
  /** 删除商城热门推荐属性 */
  DeleteShopHotItem(request: StringValue): Promise<Empty>;
  /** 设置状态 */
  SetShopHotItemStatus(request: SetStatusRequest): Promise<Empty>;
}
