// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: admin/user_store.proto

/* eslint-disable */
import { type UserStoreStatus } from "../common/enum";
import { type Empty } from "../google/protobuf/empty";
import { type Int64Value } from "../google/protobuf/wrappers";

export interface PageUserStoreRequest {
  /** 门店名称 */
  name: string;
  /** 状态 */
  status?:
    | UserStoreStatus
    | undefined;
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageUserStoreResponse {
  /** 分页数据 */
  list: UserStore[];
  /** 总数 */
  total: number;
}

export interface AuditUserStoreForm {
  /** 用户门店ID */
  id: number;
  /** 状态 */
  status: UserStoreStatus;
  /** 备注名 */
  remark: string;
}

/** 用户门店信息 */
export interface UserStore {
  /** 用户门店ID */
  id: number;
  /** 门店名称 */
  name: string;
  /** 省市区 */
  address: string[];
  /** 详细地址 */
  detail: string;
  /** 门店照片 */
  picture: string[];
  /** 营业执照 */
  businessLicense: string[];
  /** 状态 */
  status: UserStoreStatus;
  /** 备注名 */
  remark: string;
  /** 联系人 */
  nickName: string;
  /** 手机号 */
  phone: string;
}

/** Admin用户门店管理服务 */
export interface UserStoreService {
  /** 查询用户门店列表 */
  PageUserStore(request: PageUserStoreRequest): Promise<PageUserStoreResponse>;
  /** 查询用户门店 */
  GetUserStore(request: Int64Value): Promise<UserStore>;
  /** 门店认证 */
  AuditUserStore(request: AuditUserStoreForm): Promise<Empty>;
}
