// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: gnostic/openapi/v3/openapiv3.proto

/* eslint-disable */
import { type Any as Any1 } from "../../../google/protobuf/any";

export interface AdditionalPropertiesItem {
  oneof?:
    | { $case: "schemaOrReference"; schemaOrReference: SchemaOrReference }
    | { $case: "boolean"; boolean: boolean }
    | undefined;
}

export interface Any {
  value: Any1 | undefined;
  yaml: string;
}

export interface AnyOrExpression {
  oneof?: { $case: "any"; any: Any } | { $case: "expression"; expression: Expression } | undefined;
}

/** A map of possible out-of band callbacks related to the parent operation. Each value in the map is a Path Item Object that describes a set of requests that may be initiated by the API provider and the expected responses. The key value used to identify the callback object is an expression, evaluated at runtime, that identifies a URL to use for the callback operation. */
export interface Callback {
  path: NamedPathItem[];
  specificationExtension: NamedAny[];
}

export interface CallbackOrReference {
  oneof?: { $case: "callback"; callback: Callback } | { $case: "reference"; reference: Reference } | undefined;
}

export interface CallbacksOrReferences {
  additionalProperties: NamedCallbackOrReference[];
}

/** Holds a set of reusable objects for different aspects of the OAS. All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object. */
export interface Components {
  schemas: SchemasOrReferences | undefined;
  responses: ResponsesOrReferences | undefined;
  parameters: ParametersOrReferences | undefined;
  examples: ExamplesOrReferences | undefined;
  requestBodies: RequestBodiesOrReferences | undefined;
  headers: HeadersOrReferences | undefined;
  securitySchemes: SecuritySchemesOrReferences | undefined;
  links: LinksOrReferences | undefined;
  callbacks: CallbacksOrReferences | undefined;
  specificationExtension: NamedAny[];
}

/** Contact information for the exposed API. */
export interface Contact {
  name: string;
  url: string;
  email: string;
  specificationExtension: NamedAny[];
}

export interface DefaultType {
  oneof?: { $case: "number"; number: number } | { $case: "boolean"; boolean: boolean } | {
    $case: "string";
    string: string;
  } | undefined;
}

/** When request bodies or response payloads may be one of a number of different schemas, a `discriminator` object can be used to aid in serialization, deserialization, and validation.  The discriminator is a specific object in a schema which is used to inform the consumer of the specification of an alternative schema based on the value associated with it.  When using the discriminator, _inline_ schemas will not be considered. */
export interface Discriminator {
  propertyName: string;
  mapping: Strings | undefined;
  specificationExtension: NamedAny[];
}

export interface Document {
  openapi: string;
  info: Info | undefined;
  servers: Server[];
  paths: Paths | undefined;
  components: Components | undefined;
  security: SecurityRequirement[];
  tags: Tag[];
  externalDocs: ExternalDocs | undefined;
  specificationExtension: NamedAny[];
}

/** A single encoding definition applied to a single schema property. */
export interface Encoding {
  contentType: string;
  headers: HeadersOrReferences | undefined;
  style: string;
  explode: boolean;
  allowReserved: boolean;
  specificationExtension: NamedAny[];
}

export interface Encodings {
  additionalProperties: NamedEncoding[];
}

export interface Example {
  summary: string;
  description: string;
  value: Any | undefined;
  externalValue: string;
  specificationExtension: NamedAny[];
}

export interface ExampleOrReference {
  oneof?: { $case: "example"; example: Example } | { $case: "reference"; reference: Reference } | undefined;
}

export interface ExamplesOrReferences {
  additionalProperties: NamedExampleOrReference[];
}

export interface Expression {
  additionalProperties: NamedAny[];
}

/** Allows referencing an external resource for extended documentation. */
export interface ExternalDocs {
  description: string;
  url: string;
  specificationExtension: NamedAny[];
}

/** The Header Object follows the structure of the Parameter Object with the following changes:  1. `name` MUST NOT be specified, it is given in the corresponding `headers` map. 1. `in` MUST NOT be specified, it is implicitly in `header`. 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, `style`). */
export interface Header {
  description: string;
  required: boolean;
  deprecated: boolean;
  allowEmptyValue: boolean;
  style: string;
  explode: boolean;
  allowReserved: boolean;
  schema: SchemaOrReference | undefined;
  example: Any | undefined;
  examples: ExamplesOrReferences | undefined;
  content: MediaTypes | undefined;
  specificationExtension: NamedAny[];
}

export interface HeaderOrReference {
  oneof?: { $case: "header"; header: Header } | { $case: "reference"; reference: Reference } | undefined;
}

export interface HeadersOrReferences {
  additionalProperties: NamedHeaderOrReference[];
}

/** The object provides metadata about the API. The metadata MAY be used by the clients if needed, and MAY be presented in editing or documentation generation tools for convenience. */
export interface Info {
  title: string;
  description: string;
  termsOfService: string;
  contact: Contact | undefined;
  license: License | undefined;
  version: string;
  specificationExtension: NamedAny[];
  summary: string;
}

export interface ItemsItem {
  schemaOrReference: SchemaOrReference[];
}

/** License information for the exposed API. */
export interface License {
  name: string;
  url: string;
  specificationExtension: NamedAny[];
}

/** The `Link object` represents a possible design-time link for a response. The presence of a link does not guarantee the caller's ability to successfully invoke it, rather it provides a known relationship and traversal mechanism between responses and other operations.  Unlike _dynamic_ links (i.e. links provided **in** the response payload), the OAS linking mechanism does not require link information in the runtime response.  For computing links, and providing instructions to execute them, a runtime expression is used for accessing values in an operation and using them as parameters while invoking the linked operation. */
export interface Link {
  operationRef: string;
  operationId: string;
  parameters: AnyOrExpression | undefined;
  requestBody: AnyOrExpression | undefined;
  description: string;
  server: Server | undefined;
  specificationExtension: NamedAny[];
}

export interface LinkOrReference {
  oneof?: { $case: "link"; link: Link } | { $case: "reference"; reference: Reference } | undefined;
}

export interface LinksOrReferences {
  additionalProperties: NamedLinkOrReference[];
}

/** Each Media Type Object provides schema and examples for the media type identified by its key. */
export interface MediaType {
  schema: SchemaOrReference | undefined;
  example: Any | undefined;
  examples: ExamplesOrReferences | undefined;
  encoding: Encodings | undefined;
  specificationExtension: NamedAny[];
}

export interface MediaTypes {
  additionalProperties: NamedMediaType[];
}

/** Automatically-generated message used to represent maps of Any as ordered (name,value) pairs. */
export interface NamedAny {
  /** Map key */
  name: string;
  /** Mapped value */
  value: Any | undefined;
}

/** Automatically-generated message used to represent maps of CallbackOrReference as ordered (name,value) pairs. */
export interface NamedCallbackOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: CallbackOrReference | undefined;
}

/** Automatically-generated message used to represent maps of Encoding as ordered (name,value) pairs. */
export interface NamedEncoding {
  /** Map key */
  name: string;
  /** Mapped value */
  value: Encoding | undefined;
}

/** Automatically-generated message used to represent maps of ExampleOrReference as ordered (name,value) pairs. */
export interface NamedExampleOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: ExampleOrReference | undefined;
}

/** Automatically-generated message used to represent maps of HeaderOrReference as ordered (name,value) pairs. */
export interface NamedHeaderOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: HeaderOrReference | undefined;
}

/** Automatically-generated message used to represent maps of LinkOrReference as ordered (name,value) pairs. */
export interface NamedLinkOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: LinkOrReference | undefined;
}

/** Automatically-generated message used to represent maps of MediaType as ordered (name,value) pairs. */
export interface NamedMediaType {
  /** Map key */
  name: string;
  /** Mapped value */
  value: MediaType | undefined;
}

/** Automatically-generated message used to represent maps of ParameterOrReference as ordered (name,value) pairs. */
export interface NamedParameterOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: ParameterOrReference | undefined;
}

/** Automatically-generated message used to represent maps of PathItem as ordered (name,value) pairs. */
export interface NamedPathItem {
  /** Map key */
  name: string;
  /** Mapped value */
  value: PathItem | undefined;
}

/** Automatically-generated message used to represent maps of RequestBodyOrReference as ordered (name,value) pairs. */
export interface NamedRequestBodyOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: RequestBodyOrReference | undefined;
}

/** Automatically-generated message used to represent maps of ResponseOrReference as ordered (name,value) pairs. */
export interface NamedResponseOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: ResponseOrReference | undefined;
}

/** Automatically-generated message used to represent maps of SchemaOrReference as ordered (name,value) pairs. */
export interface NamedSchemaOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: SchemaOrReference | undefined;
}

/** Automatically-generated message used to represent maps of SecuritySchemeOrReference as ordered (name,value) pairs. */
export interface NamedSecuritySchemeOrReference {
  /** Map key */
  name: string;
  /** Mapped value */
  value: SecuritySchemeOrReference | undefined;
}

/** Automatically-generated message used to represent maps of ServerVariable as ordered (name,value) pairs. */
export interface NamedServerVariable {
  /** Map key */
  name: string;
  /** Mapped value */
  value: ServerVariable | undefined;
}

/** Automatically-generated message used to represent maps of string as ordered (name,value) pairs. */
export interface NamedString {
  /** Map key */
  name: string;
  /** Mapped value */
  value: string;
}

/** Automatically-generated message used to represent maps of StringArray as ordered (name,value) pairs. */
export interface NamedStringArray {
  /** Map key */
  name: string;
  /** Mapped value */
  value: StringArray | undefined;
}

/** Configuration details for a supported OAuth Flow */
export interface OauthFlow {
  authorizationUrl: string;
  tokenUrl: string;
  refreshUrl: string;
  scopes: Strings | undefined;
  specificationExtension: NamedAny[];
}

/** Allows configuration of the supported OAuth Flows. */
export interface OauthFlows {
  implicit: OauthFlow | undefined;
  password: OauthFlow | undefined;
  clientCredentials: OauthFlow | undefined;
  authorizationCode: OauthFlow | undefined;
  specificationExtension: NamedAny[];
}

export interface Object {
  additionalProperties: NamedAny[];
}

/** Describes a single API operation on a path. */
export interface Operation {
  tags: string[];
  summary: string;
  description: string;
  externalDocs: ExternalDocs | undefined;
  operationId: string;
  parameters: ParameterOrReference[];
  requestBody: RequestBodyOrReference | undefined;
  responses: Responses | undefined;
  callbacks: CallbacksOrReferences | undefined;
  deprecated: boolean;
  security: SecurityRequirement[];
  servers: Server[];
  specificationExtension: NamedAny[];
}

/** Describes a single operation parameter.  A unique parameter is defined by a combination of a name and location. */
export interface Parameter {
  name: string;
  in: string;
  description: string;
  required: boolean;
  deprecated: boolean;
  allowEmptyValue: boolean;
  style: string;
  explode: boolean;
  allowReserved: boolean;
  schema: SchemaOrReference | undefined;
  example: Any | undefined;
  examples: ExamplesOrReferences | undefined;
  content: MediaTypes | undefined;
  specificationExtension: NamedAny[];
}

export interface ParameterOrReference {
  oneof?: { $case: "parameter"; parameter: Parameter } | { $case: "reference"; reference: Reference } | undefined;
}

export interface ParametersOrReferences {
  additionalProperties: NamedParameterOrReference[];
}

/** Describes the operations available on a single path. A Path Item MAY be empty, due to ACL constraints. The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available. */
export interface PathItem {
  Ref: string;
  summary: string;
  description: string;
  get: Operation | undefined;
  put: Operation | undefined;
  post: Operation | undefined;
  delete: Operation | undefined;
  options: Operation | undefined;
  head: Operation | undefined;
  patch: Operation | undefined;
  trace: Operation | undefined;
  servers: Server[];
  parameters: ParameterOrReference[];
  specificationExtension: NamedAny[];
}

/** Holds the relative paths to the individual endpoints and their operations. The path is appended to the URL from the `Server Object` in order to construct the full URL.  The Paths MAY be empty, due to ACL constraints. */
export interface Paths {
  path: NamedPathItem[];
  specificationExtension: NamedAny[];
}

export interface Properties {
  additionalProperties: NamedSchemaOrReference[];
}

/** A simple object to allow referencing other components in the specification, internally and externally.  The Reference Object is defined by JSON Reference and follows the same structure, behavior and rules.   For this specification, reference resolution is accomplished as defined by the JSON Reference specification and not by the JSON Schema specification. */
export interface Reference {
  Ref: string;
  summary: string;
  description: string;
}

export interface RequestBodiesOrReferences {
  additionalProperties: NamedRequestBodyOrReference[];
}

/** Describes a single request body. */
export interface RequestBody {
  description: string;
  content: MediaTypes | undefined;
  required: boolean;
  specificationExtension: NamedAny[];
}

export interface RequestBodyOrReference {
  oneof?: { $case: "requestBody"; requestBody: RequestBody } | { $case: "reference"; reference: Reference } | undefined;
}

/** Describes a single response from an API Operation, including design-time, static  `links` to operations based on the response. */
export interface Response {
  description: string;
  headers: HeadersOrReferences | undefined;
  content: MediaTypes | undefined;
  links: LinksOrReferences | undefined;
  specificationExtension: NamedAny[];
}

export interface ResponseOrReference {
  oneof?: { $case: "response"; response: Response } | { $case: "reference"; reference: Reference } | undefined;
}

/** A container for the expected responses of an operation. The container maps a HTTP response code to the expected response.  The documentation is not necessarily expected to cover all possible HTTP response codes because they may not be known in advance. However, documentation is expected to cover a successful operation response and any known errors.  The `default` MAY be used as a default response object for all HTTP codes  that are not covered individually by the specification.  The `Responses Object` MUST contain at least one response code, and it  SHOULD be the response for a successful operation call. */
export interface Responses {
  default: ResponseOrReference | undefined;
  responseOrReference: NamedResponseOrReference[];
  specificationExtension: NamedAny[];
}

export interface ResponsesOrReferences {
  additionalProperties: NamedResponseOrReference[];
}

/** The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is an extended subset of the JSON Schema Specification Wright Draft 00.  For more information about the properties, see JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema. */
export interface Schema {
  nullable: boolean;
  discriminator: Discriminator | undefined;
  readOnly: boolean;
  writeOnly: boolean;
  xml: Xml | undefined;
  externalDocs: ExternalDocs | undefined;
  example: Any | undefined;
  deprecated: boolean;
  title: string;
  multipleOf: number;
  maximum: number;
  exclusiveMaximum: boolean;
  minimum: number;
  exclusiveMinimum: boolean;
  maxLength: number;
  minLength: number;
  pattern: string;
  maxItems: number;
  minItems: number;
  uniqueItems: boolean;
  maxProperties: number;
  minProperties: number;
  required: string[];
  enum: Any[];
  type: string;
  allOf: SchemaOrReference[];
  oneOf: SchemaOrReference[];
  anyOf: SchemaOrReference[];
  not: Schema | undefined;
  items: ItemsItem | undefined;
  properties: Properties | undefined;
  additionalProperties: AdditionalPropertiesItem | undefined;
  default: DefaultType | undefined;
  description: string;
  format: string;
  specificationExtension: NamedAny[];
}

export interface SchemaOrReference {
  oneof?: { $case: "schema"; schema: Schema } | { $case: "reference"; reference: Reference } | undefined;
}

export interface SchemasOrReferences {
  additionalProperties: NamedSchemaOrReference[];
}

/** Lists the required security schemes to execute this operation. The name used for each property MUST correspond to a security scheme declared in the Security Schemes under the Components Object.  Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information.  When a list of Security Requirement Objects is defined on the OpenAPI Object or Operation Object, only one of the Security Requirement Objects in the list needs to be satisfied to authorize the request. */
export interface SecurityRequirement {
  additionalProperties: NamedStringArray[];
}

/** Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), mutual TLS (use of a client certificate), OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and OpenID Connect.   Please note that currently (2019) the implicit flow is about to be deprecated OAuth 2.0 Security Best Current Practice. Recommended for most use case is Authorization Code Grant flow with PKCE. */
export interface SecurityScheme {
  type: string;
  description: string;
  name: string;
  in: string;
  scheme: string;
  bearerFormat: string;
  flows: OauthFlows | undefined;
  openIdConnectUrl: string;
  specificationExtension: NamedAny[];
}

export interface SecuritySchemeOrReference {
  oneof?:
    | { $case: "securityScheme"; securityScheme: SecurityScheme }
    | { $case: "reference"; reference: Reference }
    | undefined;
}

export interface SecuritySchemesOrReferences {
  additionalProperties: NamedSecuritySchemeOrReference[];
}

/** An object representing a Server. */
export interface Server {
  url: string;
  description: string;
  variables: ServerVariables | undefined;
  specificationExtension: NamedAny[];
}

/** An object representing a Server Variable for server URL template substitution. */
export interface ServerVariable {
  enum: string[];
  default: string;
  description: string;
  specificationExtension: NamedAny[];
}

export interface ServerVariables {
  additionalProperties: NamedServerVariable[];
}

/** Any property starting with x- is valid. */
export interface SpecificationExtension {
  oneof?: { $case: "number"; number: number } | { $case: "boolean"; boolean: boolean } | {
    $case: "string";
    string: string;
  } | undefined;
}

export interface StringArray {
  value: string[];
}

export interface Strings {
  additionalProperties: NamedString[];
}

/** Adds metadata to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag defined in the Operation Object instances. */
export interface Tag {
  name: string;
  description: string;
  externalDocs: ExternalDocs | undefined;
  specificationExtension: NamedAny[];
}

/** A metadata object that allows for more fine-tuned XML model definitions.  When using arrays, XML element names are *not* inferred (for singular/plural forms) and the `name` property SHOULD be used to add that information. See examples for expected behavior. */
export interface Xml {
  name: string;
  namespace: string;
  prefix: string;
  attribute: boolean;
  wrapped: boolean;
  specificationExtension: NamedAny[];
}
