// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: base/config.proto

/* eslint-disable */

/** 系统配置位置 */
export enum BaseConfigSite {
  UNKNOWN_BCS = 0,
  /** SYSTEM - 系统内使用 */
  SYSTEM = 1,
  /** ADMIN - 管理端 */
  ADMIN = 2,
  /** APP - 移动端 */
  APP = 3,
}

export interface ConfigRequest {
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
}

export interface ConfigResponse {
  /** 系统配置 */
  data: ConfigResponse_Data[];
}

export interface ConfigResponse_Data {
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
}

/** 系统配置公共服务 */
export interface ConfigService {
  /** 获取系统配置 */
  GetConfig(request: ConfigRequest): Promise<ConfigResponse>;
}
