// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: base/file.proto

/* eslint-disable */
import { type BytesValue } from "../google/protobuf/wrappers";

export interface MultiUploadFileRequest {
  /** 文件名 */
  files: UploadFileInfo[];
}

export interface MultiUploadFileResponse {
  /** 文件上传结果 */
  files: FileInfo[];
}

export interface UploadFileInfo {
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
  /** 文件路径 */
  path: string;
  /** 二进制内容将通过 base64 编码传输 */
  content: Uint8Array;
}

export interface DownloadFileRequest {
  /** 文件名 */
  name: string;
  /** 文件路径 */
  path: string;
}

export interface FileInfo {
  /** 文件路径 */
  url: string;
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
}

/** 文件服务 */
export interface FileService {
  /** 多个文件上传 */
  MultiUploadFile(request: MultiUploadFileRequest): Promise<MultiUploadFileResponse>;
  /** 单个文件上传 */
  UploadFile(request: UploadFileInfo): Promise<FileInfo>;
  /** 下载文件 */
  DownloadFile(request: DownloadFileRequest): Promise<BytesValue>;
}
