// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: base/login.proto

/* eslint-disable */
import { type Empty } from "../google/protobuf/empty";

export interface CaptchaResponse {
  /** 验证码ID。 */
  captchaId: string;
  /** 验证码base64 */
  captchaBase64: string;
}

/** 用户刷新令牌 - 请求 */
export interface RefreshTokenRequest {
  /** 更新令牌，用来获取下一次的访问令牌，必选项。 */
  refreshToken: string;
}

/** 用户刷新令牌 - 回应 */
export interface RefreshTokenResponse {
  /** 访问令牌，必选项。 */
  accessToken: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refreshToken: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  tokenType: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expiresIn: number;
}

/** 用户后台登录 - 请求 */
export interface LoginRequest {
  /** 用户名，必选项。 */
  userName: string;
  /** 用户的密码，必选项。 */
  password: string;
  /** 验证码 */
  captchaCode: string;
  /** 验证码Id */
  captchaId: string;
}

/** 用户后台登录 - 回应 */
export interface LoginResponse {
  /** 访问令牌，必选项。 */
  accessToken: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refreshToken: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  tokenType: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expiresIn: number;
}

/** 登录公共服务 */
export interface LoginService {
  /** 验证码 */
  Captcha(request: Empty): Promise<CaptchaResponse>;
  /** 登出 */
  Logout(request: Empty): Promise<Empty>;
  /** 刷新认证令牌 */
  RefreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse>;
  /** 登录 */
  Login(request: LoginRequest): Promise<LoginResponse>;
}
